# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'equilibrios.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(674, 599)
        Dialog.setStyleSheet("QMainWindow{\n"
"    background:Coral;\n"
"}\n"
"\n"
"QWidget{\n"
"    background:#25252A;\n"
"}\n"
"QPushButton{\n"
"\n"
"    color:white;\n"
"    background-color:rgb(255,0,68);\n"
"    font:57 11pt \"Ubuntu\";\n"
"    border-radius:4px;\n"
"    letter-spacing: 2px;\n"
"    font-size:18px;\n"
"\n"
"    font-weight: bold\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    background-color:#25252A;\n"
"    border-color: #2d98da;\n"
"    border-width : 2px;\n"
"    border-style:inset;\n"
"    \n"
"}\n"
"QLabel{\n"
"    color:white;\n"
"    border-color:white;\n"
"    border-width : 2px;\n"
"    border-style:inset;\n"
"}\n"
"QSpinBox{\n"
"    color:white;\n"
"    border-color:white;\n"
"    background:#4b6584;\n"
"}\n"
"")
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(100, 30, 451, 311))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 380, 591, 61))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(230, 520, 181, 31))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Conjunto Solucion = {}"))
        self.pushButton.setText(_translate("Dialog", "Salir"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
