# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'integrantes.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(652, 300)
        Dialog.setStyleSheet("QMainWindow{\n"
"    background:Coral;\n"
"}\n"
"\n"
"QWidget{\n"
"    background:#25252A;\n"
"}\n"
"QPushButton{\n"
"\n"
"    color:white;\n"
"    background-color:rgb(255,0,68);\n"
"    font:57 11pt \"Ubuntu\";\n"
"    border-radius:4px;\n"
"    letter-spacing: 2px;\n"
"    font-size:18px;\n"
"\n"
"    font-weight: bold\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    background-color:#25252A;\n"
"    border-color: #2d98da;\n"
"    border-width : 2px;\n"
"    border-style:inset;\n"
"    \n"
"}\n"
"QLabel{\n"
"    color:white;\n"
"    border-color:white;\n"
"    border-width : 2px;\n"
"    border-style:inset;\n"
"}\n"
"QSpinBox{\n"
"    color:white;\n"
"    border-color:white;\n"
"    background:#4b6584;\n"
"}")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 621, 241))
        self.label.setTextFormat(QtCore.Qt.MarkdownText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Leonardo Manuel Grau Vargas - u201823031\n"
"Omar Alejandro Rumiche Hernández - u202018635\n"
"Johnny Miguel Sebastian Roque Neciosup - u201924261\n"
"Kevin Stif sánchez Urbina - u201924600\n"
"William Condori Saira - U201924394"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
